### ISSUE TITLE
Minimum PowerShell host version

### ISSUE THREAD

**Issue by datenschieber** [lizoc/textscript#1]
Running PowerShell Core 6.1.1 on Mac. TextScript in a Terminal-based PowerShell runs fine.

When I want to import the TextScript module in a Visual Studio Code PowerShell console it fails:
import-module : The current PowerShell host is: 'Visual Studio Code Host' (version 1.10.1). The module '/usr/local/share/powershell/Modules/TextScript/1.15.0.0/TextScript.psd1' requires a minimum PowerShell host version of '3.0' to run.

Is it possible to disabled the PowerShell host version check?

**Comment by imacks** [comment]
sure thing. try changing the line `PowerShellHostVersion = '3.0'` to `#PowerShellHostVersion = '3.0'` in the psd1 file.
